name: 'Automatic build'
on:
  push:
    branches:
      - 3-2-stable
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: false  # Disable cache to avoid platform issues

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local without 'development test'
          bundle install --jobs 4 --retry 3
      - name: Deploy
        run: bash tools/deploy.sh
